---
- name: Disable UFW
  ansible.builtin.service:
    name: ufw
    state: stopped

- name: Remove UFW
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Install packages
  ansible.builtin.package:
    name:
      - net-tools
      - curl
      - wget
    state: present

- name: Install k3d
  ansible.builtin.script: |
    /usr/bin/wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  args:
    creates: /usr/local/bin/k3d
  register: k3dinst

- name: Debug
  ansible.builtin.debug:
    var: k3dinst

- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ ansible_awx_k3d_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  tags:
    kubeinst
