---
- name: Assert AWX Operator version
  ansible.builtin.assert:
    quiet: true
    that:
      - ansible_awx_k3d_awx_operator_version is defined
      - ansible_awx_k3d_awx_operator_version | length > 0

- name: Show IP of public_domain
  ansible.builtin.debug:
    msg:
      - "public_domain: {{ public_domain }}"
      - "IP:            {{ lookup('community.general.dig', public_domain + '.') }}"
  become: false

- name: Check if IP from public_domain is in ansible_all_ipv4_addresses
  ansible.builtin.assert:
    quiet: true
    that:
      - lookup('community.general.dig', public_domain + '.') in ansible_all_ipv4_addresses
  become: false

- name: Set namespace to awx
  tags:
    - kubenamespace
  ansible.builtin.command: kubectl config set-context --current --namespace=awx

- name: Create deployment directory
  ansible.builtin.file:
    dest: "{{ ansible_awx_k3d_kustomize_target }}"
    state: directory
    mode: '0755'

- name: Create kustomize configuration
  ansible.builtin.template:
    src: kustomization.yaml.j2
    dest: "{{ ansible_awx_k3d_kustomize_target }}/kustomization.yaml"
    backup: true
    mode: '0644'

- name: AWX-instance configuration
  ansible.builtin.template:
    src: awx-instance.yml.j2
    dest: "{{ ansible_awx_k3d_kustomize_target }}/awx-instance.yml"
    backup: true
    mode: '0644'

- name: Deploy awx
  block:
    - name: Deploy with kustomize
      ansible.builtin.shell: |
        set -eu
        set -o pipefail
        /usr/local/bin/kubectl config set-context --current --namespace=awx
        /usr/local/bin/kubectl kustomize . | tee - | /usr/local/bin/kubectl apply -f -
      args:
        chdir: "{{ ansible_awx_k3d_kustomize_target }}"
        executable: /bin/bash

      register: kustomize

  always:
    - name: Debug
      ansible.builtin.debug:
        var: kustomize
